name: maven ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: build
        run: mvn -B clean test spotbugs:spotbugs spotbugs:check spotbugs:verify package

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: iban-validator
          path: target/*.jar
