name: maven ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: build
        run: mvn -B clean test spotbugs:spotbugs spotbugs:check spotbugs:verify package

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: iban-validator
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: download jar from build action
        uses: actions/download-artifact@v4
        with:
          name: iban-validator
          path: target

      - name: create gh release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
